<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tabla[
    <!ELEMENT tabla (grupos, bloques, periodos, elementos)>
    
    <!ELEMENT grupos (grupo+)>
    <!ELEMENT grupo (id, codigo, nombre, descripcion)>
    <!ATTLIST grupo id ID #REQUIRED>
    <!ELEMENT id (ANY)>
    <!ELEMENT codigo (ANY)>
    <!ELEMENT nombre (ANY)>
    <!ELEMENT descripcion (ANY)>

    <!ELEMENT bloques (bloque+)>
    <!ELEMENT bloque (id, codigo, nombre)>
    <!ATTLIST bloque id ID #REQUIRED>
    <!ELEMENT id (ANY)>
    <!ELEMENT codigo (ANY)>
    <!ELEMENT nombre (ANY)>

    <!ELEMENT periodos (periodo+)>
    <!ELEMENT periodo (id, fila, codigo, bloque)>
    <!ATTLIST periodo id ID #REQUIRED>
    <!ELEMENT id (ANY)>
    <!ELEMENT fila (ANY)>
    <!ELEMENT codigo (ANY)>
    <!ELEMENT bloque (ANY)>

    <!ELEMENT elementos (elemento+)>
    <!ELEMENT periodo (numero, nombre, simbolo, peso, densidad, fusion, ebullicion, descubrimiento, grupo, bloque, periodo)>
    <!ATTLIST periodo id ID #REQUIRED>
    <!ATTLIST periodo refGrupo CDATA "">
    <!ATTLIST periodo refBloque CDATA "">
    <!ATTLIST periodo refPeriodo CDATA "">
    <!ELEMENT numero (ANY)>
    <!ELEMENT nombre (ANY)>
    <!ELEMENT simbolo (ANY)>
    <!ELEMENT peso (ANY)>
    <!ELEMENT densidad (ANY)>
    <!ELEMENT fusion (ANY)>
    <!ELEMENT ebullicion (ANY)>    
    <!ELEMENT grupo (ANY)>
    <!ELEMENT bloque (ANY)>
    <!ELEMENT periodo (ANY)>
    <!ELEMENT descubrimiento (epoca, inicio, fin)>
    <!ELEMENT epoca (ANY)>
    <!ELEMENT inicio (ANY)>
    <!ELEMENT fin (ANY)>
]>
<tabla>
    <grupos>
        <grupo id="1">
            <id>1</id>
            <codigo>I A</codigo>
            <nombre>metales alcalinos</nombre>
            <descripcion>
                Grupo 1 (I A): metales alcalinos
            </descripcion>
        </grupo>
        <grupo id="2">
            <id>2</id>
            <codigo>II A</codigo>
            <nombre>metales alcalinotérreos</nombre>
            <descripcion>
                Grupo 2 (II A): metales alcalinotérreos
            </descripcion>
        </grupo>
        <grupo id="3">
            <id>3</id>
            <codigo>III B</codigo>
            <nombre>familia del escandio</nombre>
            <descripcion>
                Grupo 3 (III B): familia del escandio (tierras raras y actinidos)
            </descripcion>
        </grupo>
        <grupo id="4">
            <id>4</id>
            <codigo>IV B</codigo>
            <nombre>familia del titanio</nombre>
            <descripcion>
                Grupo 4 (IV B): familia del titanio
            </descripcion>
        </grupo>
        <grupo id="5">
            <id>5</id>
            <codigo>V B</codigo>
            <nombre>familia del vanadio</nombre>
            <descripcion>
                Grupo 5 (V B): familia del vanadio
            </descripcion>
        </grupo>
        <grupo id="6">
            <id>6</id>
            <codigo>VI B</codigo>
            <nombre>familia del cromo</nombre>
            <descripcion>
                Grupo 6 (VI B): familia del cromo
            </descripcion>
        </grupo>
        <grupo id="7">
            <id>7</id>
            <codigo>VII B</codigo>
            <nombre>familia del manganeso</nombre>
            <descripcion>
                Grupo 7 (VII B): familia del manganeso
            </descripcion>
        </grupo>
        <grupo id="8">
            <id>8</id>
            <codigo>VIII B</codigo>
            <nombre>familia del hierro</nombre>
            <descripcion>
                Grupo 8 (VIII B): familia del hierro
            </descripcion>
        </grupo>
        <grupo id="9">
            <id>9</id>
            <codigo>VIII B</codigo>
            <nombre>familia del cobalto</nombre>
            <descripcion>
                Grupo 9 (VIII B): familia del cobalto
            </descripcion>
        </grupo>
        <grupo id="10">
            <id>10</id>
            <codigo>VIII B</codigo>
            <nombre>familia del níquel</nombre>
            <descripcion>
                Grupo 10 (VIII B): familia del níquel
            </descripcion>
        </grupo>
        <grupo id="11">
            <id>11</id>
            <codigo>I B</codigo>
            <nombre>familia del cobre</nombre>
            <descripcion>
                Grupo 11 (I B): familia del cobre
            </descripcion>
        </grupo>
        <grupo id="12">
            <id>12</id>
            <codigo>II B</codigo>
            <nombre>familia del zinc</nombre>
            <descripcion>
                Grupo 12 (II B): familia del zinc
            </descripcion>
        </grupo>
        <grupo id="13">
            <id>13</id>
            <codigo>III A</codigo>
            <nombre>térreos</nombre>
            <descripcion>
                Grupo 13 (III A): térreos
            </descripcion>
        </grupo>
        <grupo id="14">
            <id>14</id>
            <codigo>IV A</codigo>
            <nombre>carbonoideos</nombre>
            <descripcion>
                Grupo 14 (IV A): carbonoideos
            </descripcion>
        </grupo>
        <grupo id="15">
            <id>15</id>
            <codigo>V A</codigo>
            <nombre>nitrogenoideos</nombre>
            <descripcion>
                Grupo 15 (V A): nitrogenoideos
            </descripcion>
        </grupo>
        <grupo id="16">
            <id>16</id>
            <codigo>VI A)</codigo>
            <nombre>calcógenos o anfígenos</nombre>
            <descripcion>
                Grupo 16 (VI A): calcógenos o anfígenos
            </descripcion>
        </grupo>
        <grupo id="17">
            <id>17</id>
            <codigo>VII A</codigo>
            <nombre>halógenos</nombre>
            <descripcion>
                Grupo 17 (VII A): halógenos
            </descripcion>
        </grupo>
        <grupo id="18">
            <id>18</id>
            <codigo>VIII A</codigo>
            <nombre>gases nobles</nombre>
            <descripcion>
                Grupo 18 (VIII A): gases nobles
            </descripcion>
        </grupo>
    </grupos>
    <bloques>
        <bloque id="1">
            <id>1</id>
            <codigo>s</codigo>
            <nombre>Bloque s</nombre>
        </bloque>
        <bloque id="2">
            <id>2</id>
            <codigo>p</codigo>
            <nombre>Bloque p</nombre>
        </bloque>
        <bloque id="3">
            <id>3</id>
            <codigo>d</codigo>
            <nombre>Bloque d</nombre>
        </bloque>
        <bloque id="4">
            <id>4</id>
            <codigo>f</codigo>
            <nombre>Bloque f</nombre>
        </bloque>
    </bloques>
    <periodos>
        <periodo id="1">
            <id>1</id>
            <fila>1</fila>
            <codigo>1s</codigo>
            <bloque>s</bloque>
        </periodo>
        <periodo id="2">
            <id>2</id>
            <fila>2</fila>
            <codigo>2s</codigo>
            <bloque>s</bloque>
        </periodo>
        <periodo id="3">
            <id>3</id>
            <fila>3</fila>
            <codigo>3s</codigo>
            <bloque>s</bloque>
        </periodo>
        <periodo id="4">
            <id>4</id>
            <fila>4</fila>
            <codigo>4s</codigo>
            <bloque>s</bloque>
        </periodo>
        <periodo id="5">
            <id>5</id>
            <fila>5</fila>
            <codigo>5s</codigo>
            <bloque>s</bloque>
        </periodo>
        <periodo id="6">
            <id>6</id>
            <fila>6</fila>
            <codigo>6s</codigo>
            <bloque>s</bloque>
        </periodo>
        <periodo id="7">
            <id>7</id>
            <fila>7</fila>
            <codigo>7s</codigo>
            <bloque>s</bloque>
        </periodo>
        <periodo id="8">
            <id>8</id>
            <fila>8</fila>
            <codigo>4f</codigo>
            <bloque>f</bloque>
        </periodo>
        <periodo id="9">
            <id>9</id>
            <fila>9</fila>
            <codigo>5f</codigo>
            <bloque>f</bloque>
        </periodo>
        <periodo id="10">
            <id>10</id>
            <fila>4</fila>
            <codigo>3d</codigo>
            <bloque>d</bloque>
        </periodo>
        <periodo id="11">
            <id>11</id>
            <fila>5</fila>
            <codigo>4d</codigo>
            <bloque>d</bloque>
        </periodo>
        <periodo id="12">
            <id>12</id>
            <fila>6</fila>
            <codigo>5d</codigo>
            <bloque>d</bloque>
        </periodo>
        <periodo id="13">
            <id>13</id>
            <fila>7</fila>
            <codigo>6d</codigo>
            <bloque>d</bloque>
        </periodo>
        <periodo id="14">
            <id>14</id>
            <fila>2</fila>
            <codigo>2p</codigo>
            <bloque>p</bloque>
        </periodo>
        <periodo id="15">
            <id>15</id>
            <fila>3</fila>
            <codigo>3p</codigo>
            <bloque>p</bloque>
        </periodo>
        <periodo id="16">
            <id>16</id>
            <fila>4</fila>
            <codigo>4p</codigo>
            <bloque>p</bloque>
        </periodo>
        <periodo id="15">
            <id>15</id>
            <fila>5</fila>
            <codigo>5p</codigo>
            <bloque>p</bloque>
        </periodo>
        <periodo id="16">
            <id>16</id>
            <fila>6</fila>
            <codigo>6p</codigo>
            <bloque>p</bloque>
        </periodo>
    </periodos>
    <elementos>
        <elemento id="1" refGrupo="1" refBloque="1" refPeriodo="1">
            <numero>1</numero>
            <nombre>Hidrógeno</nombre>
            <simbolo>H</simbolo>
            <peso>1.00794</peso>
            <densidad>0.084</densidad>
            <fusion>-259.1</fusion>
            <ebullicion>-252.69</ebullicion>            
            <grupo>1</grupo>
            <bloque>1</bloque>
            <periodo>1</periodo>
            <descubrimiento>1766</descubrimiento>
        </elemento>
        <elemento id="2" refGrupo="18" refBloque="3" refPeriodo="1">
            <numero>2</numero>
            <nombre>Helio</nombre>
            <simbolo>He</simbolo>
            <peso>4.002602</peso>
            <densidad>0.17</densidad>
            <fusion>-272.2</fusion>
            <ebullicion>-268.9</ebullicion>            
            <grupo>1</grupo>
            <bloque>3</bloque>
            <periodo>18</periodo>
            <descubrimiento>1895</descubrimiento>
        </elemento>
        <elemento id="3" refGrupo="1" refBloque="1" refPeriodo="2">
            <numero>3</numero>
            <nombre>Litio</nombre>
            <simbolo>Li</simbolo>
            <peso>6.941</peso>
            <densidad>0.53</densidad>
            <fusion>180.5</fusion>
            <ebullicion>1317</ebullicion>            
            <grupo>1</grupo>
            <bloque>1</bloque>
            <periodo>2</periodo>
            <descubrimiento>1817</descubrimiento>
        </elemento>
        <elemento id="4" refGrupo="2" refBloque="1" refPeriodo="2">
            <numero>4</numero>
            <nombre>Berilio</nombre>
            <simbolo>Be</simbolo>
            <peso>9.012182</peso>
            <densidad>1.85</densidad>
            <fusion>1278</fusion>
            <ebullicion>2970</ebullicion>
            <grupo>2</grupo>
            <bloque>1</bloque>
            <periodo>2</periodo>
            <descubrimiento>1797</descubrimiento>
        </elemento>
        <elemento id="5" refGrupo="13" refBloque="" refPeriodo="">
            <numero>5</numero>
            <nombre>Boro</nombre>
            <simbolo>B</simbolo>
            <peso>10.811</peso>
            <densidad>2.46</densidad>
            <fusion>2300</fusion>
            <ebullicion>2550</ebullicion>
            <grupo>13</grupo>
            <bloque>2</bloque>
            <periodo>2</periodo>
            <descubrimiento>1808</descubrimiento>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>6</numero>
            <nombre>Carbono</nombre>
            <simbolo>C</simbolo>
            <peso>2.0107</peso>
            <densidad>3.51</densidad>
            <fusion>3550</fusion>
            <ebullicion>4827</ebullicion>
            <descubrimiento esPrehistoria="Prehistoria">0</descubrimiento>
            <grupo>14</grupo>
            <bloque>2</bloque>
            <periodo>2</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>7</numero>
            <nombre>Nitrógeno</nombre>
            <simbolo>N</simbolo>
            <peso>14.0067</peso>
            <densidad>1.17</densidad>
            <fusion>-209.9</fusion>
            <ebullicion>-195.8</ebullicion>
            <descubrimiento>1772</descubrimiento>
            <grupo>15</grupo>
            <bloque>2</bloque>
            <periodo>2</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>8</numero>
            <nombre>Oxígeno</nombre>
            <simbolo>O</simbolo>
            <peso>15.9994</peso>
            <densidad>1.33</densidad>
            <fusion>-218.4</fusion>
            <ebullicion>-182.9</ebullicion>
            <descubrimiento>1774</descubrimiento>
            <grupo>15</grupo>
            <bloque>2</bloque>
            <periodo>2</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>9</numero>
            <nombre>Flúor</nombre>
            <simbolo>F</simbolo>
            <peso>18.9984032</peso>
            <densidad>1.58</densidad>
            <fusion>-219.6</fusion>
            <ebullicion>-188.1</ebullicion>
            <descubrimiento>1886</descubrimiento>
            <grupo>17</grupo>
            <bloque>2</bloque>
            <periodo>2</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>10</numero>
            <nombre>Neón</nombre>
            <simbolo>Ne</simbolo>
            <peso>20.1797</peso>
            <densidad>0.84</densidad>
            <fusion>-248.7</fusion>
            <ebullicion>-246.1</ebullicion>
            <descubrimiento>1898</descubrimiento>
            <grupo>18</grupo>
            <bloque>2</bloque>
            <periodo>2</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>11</numero>
            <nombre>Sodio</nombre>
            <simbolo>Na</simbolo>
            <peso>22.98976928</peso>
            <densidad>0.97</densidad>
            <fusion>97.8</fusion>
            <ebullicion>892</ebullicion>
            <descubrimiento>1807</descubrimiento>
            <grupo>3</grupo>
            <bloque>1</bloque>
            <periodo>1</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>12</numero>
            <nombre>Magnesio</nombre>
            <simbolo>Mg</simbolo>
            <peso>24.3050</peso>
            <densidad>1.74</densidad>
            <fusion>648.8</fusion>
            <ebullicion>1107</ebullicion>
            <descubrimiento>1755</descubrimiento>
            <grupo>3</grupo>
            <bloque>1</bloque>
            <periodo>2</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>13</numero>
            <nombre>Aluminio</nombre>
            <simbolo>Al</simbolo>
            <peso>26.9815386</peso>
            <densidad>2.70</densidad>
            <fusion>660.5</fusion>
            <ebullicion>2467</ebullicion>
            <descubrimiento>1825</descubrimiento>
            <grupo>13</grupo>
            <bloque>2</bloque>
            <periodo>3</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>14</numero>
            <nombre>Silicio</nombre>
            <simbolo>Si</simbolo>
            <peso>28.0855</peso>
            <densidad>2.33</densidad>
            <fusion>1410</fusion>
            <ebullicion>2355</ebullicion>
            <descubrimiento>1824</descubrimiento>
            <grupo>13</grupo>
            <bloque>2</bloque>
            <periodo>3</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>15</numero>
            <nombre>Fósforo</nombre>
            <simbolo>P</simbolo>
            <peso>30.973762</peso>
            <densidad>1.82</densidad>
            <fusion>44 (P4)</fusion>
            <ebullicion>280 (P4)</ebullicion>
            <descubrimiento>1669</descubrimiento>
            <grupo>15</grupo>
            <bloque>2</bloque>
            <periodo>3</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>16</numero>
            <nombre>Azufre</nombre>
            <simbolo>S</simbolo>
            <peso>32.065</peso>
            <densidad>2.06</densidad>
            <fusion>113</fusion>
            <ebullicion>444.7</ebullicion>
            <descubrimiento esPrehistoria="Prehistoria">0</descubrimiento>
            <grupo>16</grupo>
            <bloque>2</bloque>
            <periodo>3</periodo>
        </elemento> 
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>17</numero>
            <nombre>Cloro</nombre>
            <simbolo>Cl</simbolo>
            <peso>35.453</peso>
            <densidad>2.95</densidad>
            <fusion>-34.6</fusion>
            <ebullicion>-101</ebullicion>
            <descubrimiento>1774</descubrimiento>
            <grupo>17</grupo>
            <bloque>2</bloque>
            <periodo>3</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>18</numero>
            <nombre>Argón</nombre>
            <simbolo>Ar</simbolo>
            <peso>39.948</peso>
            <densidad>1.66</densidad>
            <fusion>-189.4</fusion>
            <ebullicion>-185.9</ebullicion>
            <descubrimiento>1894</descubrimiento>
            <grupo>18</grupo>
            <bloque>2</bloque>
            <periodo>3</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>19</numero>
            <nombre>Potasio</nombre>
            <simbolo>K</simbolo>
            <peso>39.0983</peso>
            <densidad>0.86</densidad>
            <fusion>63.7</fusion>
            <ebullicion>774</ebullicion>
            <descubrimiento>1807</descubrimiento>
            <grupo>1</grupo>
            <bloque>1</bloque>
            <periodo>4</periodo>
        </elemento>
         <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>20</numero>
            <nombre>Calcio</nombre>
            <simbolo>Ca</simbolo>
            <peso>40.078</peso>
            <densidad>1.54</densidad>
            <fusion>839</fusion>
            <ebullicion>1487</ebullicion>
            <descubrimiento>1808</descubrimiento>
            <grupo>2</grupo>
            <bloque>1</bloque>
            <periodo>4</periodo>
        </elemento>
         <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>21</numero>
            <nombre>Escandio</nombre>
            <simbolo>Sc</simbolo>
            <peso>44.955912</peso>
            <densidad>1.54</densidad>
            <fusion>839</fusion>
            <ebullicion>1487</ebullicion>
            <descubrimiento>1808</descubrimiento>
            <grupo>3</grupo>
            <bloque>3</bloque>
            <periodo>4</periodo>
        </elemento>
         <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>22</numero>
            <nombre>Titanio</nombre>
            <simbolo>Ti</simbolo>
            <peso>47.867</peso>
            <densidad>4.51</densidad>
            <fusion>1660</fusion>
            <ebullicion>1487</ebullicion>
            <descubrimiento>1791</descubrimiento>
            <grupo>4</grupo>
            <bloque>3</bloque>
            <periodo>4</periodo>
        </elemento>
         <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>23</numero>
            <nombre>Vanadio</nombre>
            <simbolo>V</simbolo>
            <peso>50.9415</peso>
            <densidad>6.09</densidad>
            <fusion>1890</fusion>
            <ebullicion>3380</ebullicion>
            <descubrimiento>1801</descubrimiento>
            <grupo>5</grupo>
            <bloque>3</bloque>
            <periodo>4</periodo>
        </elemento>
         <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>24</numero>
            <nombre>Cromo</nombre>
            <simbolo>Cr</simbolo>
            <peso>51.9961</peso>
            <densidad>7.14</densidad>
            <fusion>1857</fusion>
            <ebullicion>2482</ebullicion>
            <descubrimiento>1797</descubrimiento>
            <grupo>6</grupo>
            <bloque>3</bloque>
            <periodo>4</periodo>
        </elemento>
         <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>25</numero>
            <nombre>Manganeso</nombre>
            <simbolo>Mn</simbolo>
            <peso>54.938045</peso>
            <densidad>7.44</densidad>
            <fusion>1244</fusion>
            <ebullicion>2097</ebullicion>
            <descubrimiento>1774</descubrimiento>
            <grupo>7</grupo>
            <bloque>3</bloque>
            <periodo>4</periodo>
        </elemento>
         <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>26</numero>
            <nombre>Hierro</nombre>
            <simbolo>Fe</simbolo>
            <peso>55.845</peso>
            <densidad>7.87</densidad>
            <fusion>1535</fusion>
            <ebullicion>2750</ebullicion>
            <descubrimiento esPrehistoria="Prehistoria">0</descubrimiento>
            <grupo>8</grupo>
            <bloque>3</bloque>
            <periodo>4</periodo>
        </elemento>
         <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>27</numero>
            <nombre>Cobalto</nombre>
            <simbolo>Co</simbolo>
            <peso>58.933200</peso>
            <densidad>8.89</densidad>
            <fusion>1495</fusion>
            <ebullicion>2870</ebullicion>
            <descubrimiento>1735</descubrimiento>
            <grupo>9</grupo>
            <bloque>3</bloque>
            <periodo>4</periodo>
        </elemento>
         <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>28</numero>
            <nombre>Níquel</nombre>
            <simbolo>Ni</simbolo>
            <peso>58.6934</peso>
            <densidad>8.91</densidad>
            <fusion>1453</fusion>
            <ebullicion>2732</ebullicion>
            <descubrimiento>1751</descubrimiento>
            <grupo>10</grupo>
            <bloque>3</bloque>
            <periodo>4</periodo>
        </elemento>
         <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>29</numero>
            <nombre>Cobre</nombre>
            <simbolo>Cu</simbolo>
            <peso>63.546</peso>
            <densidad>8.92</densidad>
            <fusion>1083.5</fusion>
            <ebullicion>2595</ebullicion>
            <descubrimiento esPrehistoria="Prehistoria">0</descubrimiento>
            <grupo>11</grupo>
            <bloque>3</bloque>
            <periodo>4</periodo>
        </elemento>
         <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>30</numero>
            <nombre>Zinc</nombre>
            <simbolo>Zn</simbolo>
            <peso>65.409</peso>
            <densidad>7.14</densidad>
            <fusion>419.6</fusion>
            <ebullicion>907</ebullicion>
            <descubrimiento esPrehistoria="Prehistoria">0</descubrimiento>
            <grupo>12</grupo>
            <bloque>3</bloque>
            <periodo>4</periodo>
        </elemento>
         <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>31</numero>
            <nombre>Galio</nombre>
            <simbolo>Ga</simbolo>
            <peso>69.723</peso>
            <densidad>5.91</densidad>
            <fusion>29.8</fusion>
            <ebullicion>2403</ebullicion>
            <descubrimiento>1875</descubrimiento>
            <grupo>13</grupo>
            <bloque>2</bloque>
            <periodo>4</periodo>
        </elemento>
         <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>32</numero>
            <nombre>Germanio</nombre>
            <simbolo>Ge</simbolo>
            <peso>72.64</peso>
            <densidad>5.32</densidad>
            <fusion>937.4</fusion>
            <ebullicion>2830</ebullicion>
            <descubrimiento>1886</descubrimiento>
            <grupo>14</grupo>
            <bloque>2</bloque>
            <periodo>4</periodo>
        </elemento>
         <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>33</numero>
            <nombre>Arsénico</nombre>
            <simbolo>As</simbolo>
            <peso>74.92160</peso>
            <densidad>5.72</densidad>
            <fusion>613</fusion>
            <ebullicion>613 (subliminación)</ebullicion>
            <descubrimiento>1250</descubrimiento>
            <grupo>15</grupo>
            <bloque>2</bloque>
            <periodo>4</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>34</numero>
            <nombre>Selenio</nombre>
            <simbolo>Se</simbolo>
            <peso>78.96</peso>
            <densidad>4.82</densidad>
            <fusion>217</fusion>
            <ebullicion>685</ebullicion>
            <descubrimiento>1817</descubrimiento>
            <grupo>16</grupo>
            <bloque>2</bloque>
            <periodo>4</periodo>
        </elemento> 
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>35</numero>
            <nombre>Bromo</nombre>
            <simbolo>Br</simbolo>
            <peso>79.904</peso>
            <densidad>3.14</densidad>
            <fusion>-7.3</fusion>
            <ebullicion>58.8</ebullicion>
            <descubrimiento>1826</descubrimiento>
            <grupo>17</grupo>
            <bloque>2</bloque>
            <periodo>4</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>35</numero>
            <nombre>Bromo</nombre>
            <simbolo>Br</simbolo>
            <peso>79.904</peso>
            <densidad>3.14</densidad>
            <fusion>-7.3</fusion>
            <ebullicion>58.8</ebullicion>
            <descubrimiento>1826</descubrimiento>
            <grupo>17</grupo>
            <bloque>2</bloque>
            <periodo>4</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>36</numero>
            <nombre>Kriptón</nombre>
            <simbolo>Kr</simbolo>
            <peso>83.798</peso>
            <densidad>3.48</densidad>
            <fusion>-156.6</fusion>
            <ebullicion>-152.3</ebullicion>
            <descubrimiento>1898</descubrimiento>
            <grupo>18</grupo>
            <bloque>2</bloque>
            <periodo>4</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>37</numero>
            <nombre>Rubidio</nombre>
            <simbolo>Kr</simbolo>
            <peso>85.4678</peso>
            <densidad>1.53</densidad>
            <fusion>39</fusion>
            <ebullicion>688</ebullicion>
            <descubrimiento>1861</descubrimiento>
            <grupo>1</grupo>
            <bloque>1</bloque>
            <periodo>5</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>38</numero>
            <nombre>Estroncio</nombre>
            <simbolo>Sr</simbolo>
            <peso>87.62</peso>
            <densidad>2.63</densidad>
            <fusion>769</fusion>
            <ebullicion>1384</ebullicion>
            <descubrimiento>1790</descubrimiento>
            <grupo>2</grupo>
            <bloque>1</bloque>
            <periodo>5</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>39</numero>
            <nombre>Itrio</nombre>
            <simbolo>Y</simbolo>
            <peso>88.90585</peso>
            <densidad>4.47</densidad>
            <fusion>1523</fusion>
            <ebullicion>3337</ebullicion>
            <descubrimiento>1794</descubrimiento>
            <grupo>3</grupo>
            <bloque>3</bloque>
            <periodo>5</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>40</numero>
            <nombre>Zirconio</nombre>
            <simbolo>Zr</simbolo>
            <peso>91.224</peso>
            <densidad>6.51</densidad>
            <fusion>1852</fusion>
            <ebullicion>4377</ebullicion>
            <descubrimiento>1789</descubrimiento>
            <grupo>4</grupo>
            <bloque>3</bloque>
            <periodo>5</periodo>
        </elemento>
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>41</numero>
            <nombre>Niobio</nombre>
            <simbolo>Nb</simbolo>
            <peso>92.906 38</peso>
            <densidad>8.58</densidad>
            <fusion>2468</fusion>
            <ebullicion>4927</ebullicion>
            <descubrimiento>1801</descubrimiento>
            <grupo>5</grupo>
            <bloque>3</bloque>
            <periodo>5</periodo>
        </elemento>                                                                                          
        <elemento id="" refGrupo="" refBloque="" refPeriodo="">
            <numero>42</numero>